### ISSUE TITLE
Access to bertir/bert/models/cw-descinit-firstp-fold5 

### ISSUE THREAD

**Issue by nguyenvo09** [AdeDZY/SIGIR19-BERT-IR#4]
I might miss something but could you grant access to the above bucket? so that I can run experiments. Thank you.

**Comment by AdeDZY** [comment]
Hi,

I'm afraid that I cannot grant the access due to the copyright of the two
datasets.

For ClueWeb09, if you already have a license, you can download the data
from our CMU server  (here
<http://boston.lti.cs.cmu.edu/appendices/SIGIR2019-Zhuyun-Dai/>). Then you
can upload them to your own google cloud bucket.

For Robust04, the best I can do is to provide the initial document rankings
(also here <http://boston.lti.cs.cmu.edu/appendices/SIGIR2019-Zhuyun-Dai/>),
and the scripts to generate passages from documents.

I am really sorry for not being able to make it more convenient. I hope you
can understand the license issue.

Best,
Zhuyun
